version: 0.2

phases:
  pre_build:
    commands:
      - echo "1. pre build step"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com
  
    on-failure: ABORT
  build:
    commands:
      - echo "2. Build step"
      - docker build -f ./Dockerfile -t custom-nginx:latest .
  post_build:
    commands:
      - echo 3.1 "Post build"
      - docker tag custom-nginx:latest $REPO_URI:latest
      - docker push $REPO_URI:latest
      - echo "3.2 Create image definitions --------"
      - printf "[{\"name\":\"webserver\",\"imageUri\":\"$REPO_URI:latest\"}]" >> imagedefinitions.json
      - cat imagedefinitions.json
    on-failure: ABORT

artifacts:
  files:
    - codedeploy/**/*
    - appspec.yml
    - docker-compose.yml
    - .env
    - imagedefinitions.json
